metrics:
  global:
    scrape_interval: 15s
  configs:
    - name: hosted-prometheus
      scrape_configs:
        - job_name: node
          static_configs:
            - targets: ["localhost:8080"]
          metrics_path: "/api/metrics"

        - job_name: promotheus
          static_configs:
            - targets: ["localhost:9090"]
      remote_write:
        - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
          basic_auth:
            username: 1107020
            password: glc_eyJvIjoiOTA3MjQ1IiwibiI6ImNvZGVkcmFmdHMiLCJrIjoiZW5KQ2w1NVAzNDRQMjJCTWI5TDd0bng4IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMSJ9fQ==
